'use client';

import { ExpenseCategory, EXPENSE_CATEGORIES, EXPENSE_CATEGORY_LABELS, MonthlySettlement, ProjectData, Task } from '@/types/project';

type Props = {
  project: ProjectData;
  updateBudget: (category: ExpenseCategory, amount: number) => void;
  updateMonthlySettlement: (updates: Partial<MonthlySettlement>) => void;
  updateTask: (taskId: string, updates: Partial<Task>) => void;
  addTask: (title: string, moduleId: 'Finance', status: string) => void;
  onBackToTasks: () => void;
};

function BudgetInput({ amount, onSave }: { amount: number; onSave: (amount: number) => void }) {
  const save = (value: string) => { const parsed = Number(value); onSave(Number.isFinite(parsed) && parsed >= 0 ? parsed : 0); };
  return <input type="number" inputMode="decimal" min="0" defaultValue={amount} onBlur={(event) => save(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && event.currentTarget.blur()} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-2 py-1.5 text-sm text-indigo-300" />;
}

export function ProjectFinancePanel({ project, updateBudget, updateMonthlySettlement, updateTask, addTask, onBackToTasks }: Props) {
  const financeTasks = project.tasks.filter((task) => task.moduleId === 'Finance');
  const totalBudget = EXPENSE_CATEGORIES.reduce((sum, category) => sum + project.budgetByCategory[category], 0);
  const actualSpend = financeTasks.filter((task) => task.isPaid).reduce((sum, task) => sum + task.amount, 0);
  const financeStatuses = project.moduleConfigs.find((config) => config.moduleId === 'Finance')?.customStatuses ?? ['📝 待請款'];
  const addExpense = () => {
    const title = window.prompt('輸入支出名稱');
    if (title?.trim()) addTask(title.trim(), 'Finance', financeStatuses[0]);
  };
  const settlement = project.monthlySettlement;
  const settlementAmount = (settlement?.deliveredCount ?? 0) * (settlement?.unitPrice ?? 0);

  return <main className="min-h-screen bg-slate-950 p-4 text-slate-100 md:p-8"><div className="mx-auto max-w-6xl">
    <header className="mb-6 flex items-center gap-4 border-b border-slate-800 pb-6"><button onClick={onBackToTasks} className="rounded-lg border border-slate-800 bg-slate-900 px-3 py-1.5 text-xs">← 返回製作任務</button><div><p className="text-xs text-indigo-400">{project.name}</p><h1 className="text-2xl font-black">💰 財務與成本控制</h1></div></header>
    {settlement ? <section className="rounded-2xl border border-indigo-800 bg-slate-900 p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-indigo-300">短影音剪輯月結</p><h2 className="mt-1 text-xl font-black">{settlement.month.replace('-', ' 年 ')} 月月結</h2></div><select value={settlement.status} onChange={(event) => updateMonthlySettlement({ status: event.target.value as MonthlySettlement['status'] })} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="pending">待請款</option><option value="invoiced">已請款</option><option value="paid">已支付</option></select></div><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm text-slate-400">月份<input type="month" value={settlement.month} onChange={(event) => updateMonthlySettlement({ month: event.target.value })} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" /></label><label className="text-sm text-slate-400">交付支數<input type="number" min="0" value={settlement.deliveredCount} onChange={(event) => updateMonthlySettlement({ deliveredCount: Math.max(0, Number(event.target.value) || 0) })} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" /></label><label className="text-sm text-slate-400">單支費用（NT$）<input type="number" min="0" value={settlement.unitPrice} onChange={(event) => updateMonthlySettlement({ unitPrice: Math.max(0, Number(event.target.value) || 0) })} className="mt-2 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100" /></label></div><p className="mt-5 border-t border-slate-800 pt-4 text-lg font-black text-emerald-400">月結金額：NT$ {settlementAmount.toLocaleString()}</p></section> : <><div className="grid gap-4 md:grid-cols-3"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs text-slate-400">預算總額</p><p className="mt-2 text-2xl font-black text-indigo-400">NT$ {totalBudget.toLocaleString()}</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs text-slate-400">實際支出</p><p className="mt-2 text-2xl font-black text-emerald-400">NT$ {actualSpend.toLocaleString()}</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs text-slate-400">預算差額</p><p className={`mt-2 text-2xl font-black ${totalBudget - actualSpend >= 0 ? 'text-amber-400' : 'text-rose-400'}`}>NT$ {(totalBudget - actualSpend).toLocaleString()}</p></section></div>
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="font-bold">階段預算</h2><p className="mt-1 text-xs text-slate-400">輸入數字後按 Enter 或離開欄位才會儲存。</p><div className="mt-4 grid gap-3 md:grid-cols-3">{EXPENSE_CATEGORIES.map((category) => { const expenses = financeTasks.filter((task) => task.expenseCategory === category); const actual = expenses.filter((task) => task.isPaid).reduce((sum, task) => sum + task.amount, 0); return <div key={category} className="rounded-xl bg-slate-950/60 p-4"><label className="text-xs text-slate-400">{EXPENSE_CATEGORY_LABELS[category]}預算<BudgetInput amount={project.budgetByCategory[category]} onSave={(amount) => updateBudget(category, amount)} /></label><p className="mt-3 text-xs text-slate-400">實際支出 <span className="float-right text-slate-100">NT$ {actual.toLocaleString()}</span></p><p className={`mt-3 border-t border-slate-800 pt-3 text-xs font-bold ${project.budgetByCategory[category] - actual >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>差額 NT$ {(project.budgetByCategory[category] - actual).toLocaleString()}</p></div>; })}</div></section>
    <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">支出項目</h2><p className="mt-1 text-xs text-slate-400">由製作任務連動或手動建立的費用。</p></div><button onClick={addExpense} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-bold hover:bg-indigo-500">＋ 新增支出</button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-slate-800 text-xs text-slate-400"><tr><th className="pb-3">項目</th><th className="pb-3">分類</th><th className="pb-3">金額</th><th className="pb-3">狀態</th><th className="pb-3">支付</th></tr></thead><tbody>{financeTasks.map((task) => <tr key={task.id} className="border-b border-slate-800/70"><td className="py-3"><input defaultValue={task.title} onBlur={(event) => { const title = event.target.value.trim(); if (title && title !== task.title) updateTask(task.id, { title }); }} className="w-full bg-transparent" /></td><td className="py-3"><select value={task.expenseCategory ?? ''} onChange={(event) => updateTask(task.id, { expenseCategory: event.target.value as ExpenseCategory || undefined })} className="rounded border border-slate-700 bg-slate-950 px-2 py-1 text-xs"><option value="">未分類</option>{EXPENSE_CATEGORIES.map((category) => <option key={category} value={category}>{EXPENSE_CATEGORY_LABELS[category]}</option>)}</select></td><td className="py-3"><input type="number" min="0" defaultValue={task.amount} onBlur={(event) => updateTask(task.id, { amount: Math.max(0, Number(event.target.value) || 0) })} className="w-28 rounded border border-slate-700 bg-slate-950 px-2 py-1 text-sm text-emerald-400" /></td><td className="py-3"><select value={task.status} onChange={(event) => updateTask(task.id, { status: event.target.value })} className="rounded border border-slate-700 bg-slate-950 px-2 py-1 text-xs">{financeStatuses.map((status) => <option key={status}>{status}</option>)}</select></td><td className="py-3"><label className="text-xs"><input type="checkbox" checked={task.isPaid} onChange={(event) => updateTask(task.id, { isPaid: event.target.checked })} /> 已支付</label></td></tr>)}{financeTasks.length === 0 && <tr><td colSpan={5} className="py-10 text-center text-sm text-slate-500">尚無支出項目</td></tr>}</tbody></table></div></section></>}
  </div></main>;
}
